### ISSUE TITLE
npm build fails

### ISSUE THREAD

**Issue by kumavis** [browserify/acorn-node#14]
```
acorn-node on  static-fix [!?] is 📦 v2.0.0 via ⬢ v12.16.1 
⇡0% ➜ yarn build
yarn run v1.22.4
$ node build.js
acorn-bigint → ./lib/bigint/index.js
acorn-numeric-separator → ./lib/numeric-separator/index.js
acorn-dynamic-import → ./lib/dynamic-import/index.js
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'acorn-dynamic-import'
Require stack:
- /home/xyz/Development/acorn-node/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at compile (/home/xyz/Development/acorn-node/build.js:11:40)
    at Object.<anonymous> (/home/xyz/Development/acorn-node/build.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/xyz/Development/acorn-node/build.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

**Comment by kumavis** [comment]
seems like incomplete removal here https://github.com/browserify/acorn-node/pull/11
